# Generated by Django 5.2 on 2025-05-04 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_customuser_name_attendanceofficerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceprocess',
            name='role',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='role',
        ),
        migrations.RemoveField(
            model_name='report',
            name='role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_type',
        ),
        migrations.AddField(
            model_name='attendanceprocess',
            name='student',
            field=models.ForeignKey(default=1, limit_choices_to={'role__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
