# Generated by Django 5.2 on 2025-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_attendanceprocess_role_remove_classroom_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Student', max_length=50),
            preserve_default=False,
        ),
    ]
