# Generated by Django 5.2 on 2025-05-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_classroom_students_customuser_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='attendance',
        ),
        migrations.AddField(
            model_name='report',
            name='attendances',
            field=models.ManyToManyField(to='main_app.attendanceprocess'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student')], max_length=50),
        ),
    ]
